enum CAMERA {
  FHAZ = "FHAZ",
  RHAZ = "RHAZ",
  MAST = "MAST",
  CHEMCAM = "CHEMCAM",
  MAHLI = "MAHLI",
  MARDI = "MARDI",
  NAVCAM = "NAVCAM",
  PANCAM = "PANCAM",
  MINITES = "MINITES",
}

export type CURIOSITY_CAMERA =
  | CAMERA.FHAZ
  | CAMERA.RHAZ
  | CAMERA.MAST
  | CAMERA.CHEMCAM
  | CAMERA.MAHLI
  | CAMERA.MARDI
  | CAMERA.NAVCAM;

export type OPPORTUNITY_CAMERA =
  | CAMERA.FHAZ
  | CAMERA.RHAZ
  | CAMERA.NAVCAM
  | CAMERA.PANCAM
  | CAMERA.MINITES;

export type SPIRIT_CAMERA = CAMERA.FHAZ | CAMERA.RHAZ | CAMERA.MINITES;
